- src/contributors/PowerbarsContributor.ts
> fix powerbars : select comma separated terms from f filter

- src/contributors/MapContributor.ts
> Change  bbox to ogc style

- src/contributors/MapContributor.ts
> Fix features display in map after changing the zoom precision

- src/contributors/ResultListContributor.ts
> Emit event when Resultlist data changed

- src/contributors/ChipsSearchContributor.ts
> Clear query string in chipsearch contributor.

- src/contributors/SwimLaneContributor.ts
> Make Swimlane contributor name configurable

- src/contributors/SwimLaneContributor.ts
> Fix : numberOfBuckets calculus doesn't set the right aggregation

- src/contributors/HistogramContributor.ts
- src/contributors/SwimLaneContributor.ts
> Fix : checking the existence of min/max in rangeResponse

- src/contributors/MapContributor.ts
> make drawType optional in Style interface

- package-lock.json
- package-release.json
- package.json
- yarn.lock
> Update arlas-web-core version to 7.1.*

- src/contributors/HistogramContributor.ts
- src/contributors/PowerbarsContributor.ts
- src/contributors/SwimLaneContributor.ts
- src/jsonSchemas/histogramContributorConf.schema.json
- src/jsonSchemas/powerbarsContributorConf.schema.json
- src/jsonSchemas/swimlaneContributorConf.schema.json
> Enable the use of metric in aggregation

- package-lock.json
- package-release.json
- package.json
- src/contributors/ChipsSearchContributor.ts
- src/contributors/DonutContributor.ts
- src/contributors/HistogramContributor.ts
- src/contributors/MapContributor.ts
- src/contributors/PowerbarsContributor.ts
- src/contributors/ResultListContributor.ts
- src/contributors/SwimLaneContributor.ts
- yarn.lock
-Fix #53
-Filter list combine with `and`
-Dropdown value updated with collaborative service
-Update core version
> Improve result list

- src/contributors/HistogramContributor.ts
> Add timeLabel property. It's calculated after :

- src/utils/histoswimUtils.ts
- when no filter is applied on the histogram
Fix #83
> include end of last bucket in intervalSelection

- src/contributors/DonutContributor.ts
> Donut fix : make arcMinPercentage configurable

- src/models/models.ts
- src/utils/histoswimUtils.ts
> Fix locale date : use utc

- package-lock.json
- src/contributors/DetailedHistogramContributor.ts
- yarn.lock
> Detailed histogram : add main histogram current selection as attribute

- src/utils/histoswimUtils.ts
> Allow decimals lower than 1 as interval of histograms

- src/contributors/DonutContributor.ts
> Fix : set size of all donut nodes at all levels

- package-lock.json
- package-release.json
- package.json
- src/contributors/MapContributor.ts
- yarn.lock
> Manage include bbox

- src/contributors/MapContributor.ts
> Improve count test map with bbox

- src/contributors/MapContributor.ts
- src/contributors/TopoMapContributor.ts
- src/index.ts
- src/jsonSchemas/topomapContributorConf.schema.json
- src/utils/mapUtils.ts
> Add TopoMapContributor

- package-lock.json
- package.json
- src/contributors/PowerbarsContributor.ts
> Implement update powerbars data

- src/contributors/DonutContributor.ts
- src/models/models.ts
> Refactor donut data type

- src/contributors/MapContributor.ts
> Emit count extend info

- src/contributors/ResultListContributor.ts
This attribute, once passed to ResultListComponent, will allow the component to specify which colmuns will be colorized by its color service
Fix #138
> ResultListContributor : Add attribute (useColorService) to fieldsList

- src/contributors/DonutContributor.ts
- src/contributors/PowerbarsContributor.ts
- src/contributors/TreeContributor.ts
- src/index.ts
- src/jsonSchemas/treeContributorConf.schema.json
- src/models/models.ts
> Implement a TreeContributor that fetches data for donuts and powerbars

- package-lock.json
- package-release.json
- package.json
- src/contributors/DetailedHistogramContributor.ts
- src/contributors/DonutContributor.ts
- src/contributors/MapContributor.ts
- src/contributors/PowerbarsContributor.ts
- src/contributors/ResultListContributor.ts
- src/contributors/TreeContributor.ts
- src/index.ts
- src/jsonSchemas/resultlistContributorConf.schema.json
- src/jsonSchemas/treeContributorConf.schema.json
- src/models/models.ts
- yarn.lock
Fix #139 
Fix #138 
Fix #128 
Fix #137
> Integrate the features of 9.2.0

- src/jsonSchemas/rootContributorConf.schema.json
> Add type property in contributor schema

- src/contributors/HistogramContributor.ts
- src/jsonSchemas/histogramContributorConf.schema.json
- src/jsonSchemas/swimlaneContributorConf.schema.json
- src/models/models.ts
- src/utils/histoswimUtils.ts
> Remove unused [dataType] attribute from Histogram contributor

- src/contributors/TopoMapContributor.ts
> Fix topomap contributor bugs

- src/contributors/MapContributor.ts
I'm not sure about this line ::
if (shortValue % 1 !== 0) { const shortNum = shortValue.toFixed(1); }
> Add new map count aggregate format

- package-lock.json
- package-release.json
- package.json
- src/contributors/MapContributor.ts
- src/contributors/ResultListContributor.ts
- yarn.lock
> Add method to force map feature mode

- package-lock.json
- src/contributors/ChipsSearchContributor.ts
Add a method for subscribing to this subject
> Remove onLastBackspace Subject from chipssearch constructor

- src/contributors/MapContributor.ts
- src/contributors/ResultListContributor.ts
>  Append id field to geosort & Flatten idFieldName in properties of a feature

- src/contributors/TreeContributor.ts
> Change tree search filter

- src/contributors/ResultListContributor.ts
- src/jsonSchemas/resultlistContributorConf.schema.json
- src/models/models.ts
- src/utils/utils.ts
> Add attachments in detailed information

- src/contributors/HistogramContributor.ts
- src/jsonSchemas/histogramContributorConf.schema.json
- src/utils/timeShortcutsUtils.ts
> Add years to time shortcut

- package-lock.json
- package-release.json
- package.json
- src/jsonSchemas/histogramContributorConf.schema.json
- yarn.lock
>  Update lock files

- package-lock.json
- src/contributors/ComputeContributor.ts
- src/jsonSchemas/computeContributorConf.schema.json
- yarn.lock
> Add process to Compute Contributor

- src/contributors/MapContributor.ts
- src/jsonSchemas/mapContributorConf.schema.json
> Enhance map configuration

- src/contributors/MapContributor.ts
- src/jsonSchemas/mapContributorConf.schema.json
> Add geoQueryOp and geoQueryField in conf

- src/contributors/ResultListContributor.ts
> Add fields declared in 'includeMetadata' list into the 'data' attribute

- src/contributors/MapContributor.ts
- src/jsonSchemas/mapContributorConf.schema.json
- src/models/models.ts
> normalize numeric and date values 

- src/contributors/MapContributor.ts
- src/jsonSchemas/mapContributorConf.schema.json
> MAP : Specify which fields are concerned by color generation

- package-lock.json
- src/contributors/SwimLaneContributor.ts
- src/jsonSchemas/swimlaneContributorConf.schema.json
> Remove redundant fields to configure in swimlane

- src/contributors/ChipsSearchContributor.ts
- src/jsonSchemas/chipssearchContributorConf.schema.json
> Centralize all the fields configuration (for search) in ChipsSearchContributor

- src/contributors/ResultListContributor.ts
> Check if sortOutput is defined before applying sort

- src/contributors/ChipsSearchContributor.ts
- src/jsonSchemas/chipssearchContributorConf.schema.json
> Centralize all the fields config (for search) in ChipsSearchContributor

- src/contributors/ResultListContributor.ts
- src/contributors/TreeContributor.ts
> Add setter for agg in tree

- src/contributors/MapContributor.ts
- src/models/models.ts
> Merge geohash tiles

- src/contributors/MapContributor.ts
> Add on option to filter with wkt

- src/contributors/MapContributor.ts
- src/contributors/TopoMapContributor.ts
- src/jsonSchemas/mapContributorConf.schema.json
> Topomap : fix bugs of features that disappear after applying a filter on other contributors

- package-lock.json
- src/contributors/MapContributor.ts
> Fix Map contributors bugs

- package-lock.json
- src/contributors/MapContributor.ts
- src/contributors/TopoMapContributor.ts
> Fix bug in displaying cluster mode in topomap

- src/contributors/MapContributor.ts
- src/contributors/TopoMapContributor.ts
- fix #295 topo mode : duplicated data when precision changes
- fix #296 cluster mode : data not updated after applying a filter
> Fix topology rendering bugs

- src/contributors/SwimLaneContributor.ts
> Refactor input data structure for swimlane contributor

- src/contributors/ResultListContributor.ts
> Fix list getActions

- package-lock.json
- package-release.json
- package.json
- src/contributors/MapContributor.ts
- src/contributors/TopoMapContributor.ts
- src/index.ts
- src/jsonSchemas/mapContributorConf.schema.json
- src/jsonSchemas/rootContributorConf.schema.json
- src/models/models.ts
- src/utils/mapUtils.ts
- src/utils/utils.ts
> implementation of map XV contributor

- src/contributors/MapContributor.ts
- src/models/models.ts
- src/utils/mapUtils.ts
- Fix some display bugs
- Render search sources progressively
- Fix raw/wrap extent bug
> Map contributor enhancements

- src/contributors/HistogramContributor.ts
- src/contributors/SwimLaneContributor.ts
- src/models/models.ts
> [Histogram][Swimlane] replace _range by _compute

- src/contributors/MapContributor.ts
- src/jsonSchemas/mapContributorConf.schema.json
- src/utils/utils.ts
> Add color generator

- src/contributors/ResultListContributor.ts
> Fix Ascending sort on columns does not work

- src/contributors/MapContributor.ts
- src/index.ts
- src/utils/utils.ts
- Mutualize includeFields & providedFields
- Fix features ids
- rgb to hex colors
> Fix Mapcontributor bugs

- src/contributors/ResultListContributor.ts
> Fix sortcolumn function

- package-lock.json
- src/contributors/MapContributor.ts
- src/models/models.ts
- src/utils/utils.ts
> Add superfinest granularity

- src/contributors/TreeContributor.ts
> Order powerbars by metrics

- src/contributors/MapContributor.ts
> Fix generated color

- package-lock.json
- src/contributors/TreeContributor.ts
- src/models/models.ts
> Add colorField for Tree

- src/contributors/DetailedHistogramContributor.ts
> Fix current selection of detailed histogram when min/max equals to 0

- src/contributors/HistogramContributor.ts
> Calculate range + clone aggregations

- src/contributors/MapContributor.ts
> Add logs in mapcontributor when data is fetched and rendered

- package-lock.json
- package-release.json
- package.json
- src/contributors/AnalyticsContributor.ts
- src/contributors/ChipsSearchContributor.ts
- src/contributors/ComputeContributor.ts
- src/contributors/DetailedHistogramContributor.ts
- src/contributors/HistogramContributor.ts
- src/contributors/MapContributor.ts
- src/contributors/ResultListContributor.ts
- src/contributors/SwimLaneContributor.ts
- src/contributors/TreeContributor.ts
- src/jsonSchemas/histogramContributorConf.schema.json
- src/utils/histoswimUtils.ts
- src/utils/utils.ts
- adapt the others to multi-collection structure
> Support multiple collections in histogram contributors

- README.md
- package-lock.json
- package-release.json
- package.json
- src/utils/histoswimUtils.ts
- #405 
- Upgrade to arlas-web-core 18.0.0
> Fix dataInterval calculus in cas of multiple charts

- src/contributors/MapContributor.ts
> Fix: add the appropriate geometry for each topology source

- src/contributors/MapContributor.ts
- src/contributors/SwimLaneContributor.ts
- src/jsonSchemas/mapContributorConf.schema.json
- src/models/models.ts
- src/utils/utils.ts
> Fetch network analytics data using xyz tiles

- .travis.yml
- src/contributors/DetailedHistogramContributor.ts
- src/contributors/HistogramContributor.ts
> Fix aggregation interval, when nbBucket is not set

- src/contributors/ResultListContributor.ts
For Safari compatibility
Fix #461
> Remove usage of lookbehind in regex

- src/contributors/MapContributor.ts
- src/contributors/ResultListContributor.ts
- Fix #463
Stringifying id values will allow us to fix this bug of ARLAS-wui
- gisaia/arlas-wui#370
> Stringify values of identifier field in map and resultlist

- src/contributors/MapContributor.ts
- src/models/models.ts
- src/utils/mapUtils.ts
> Fix loading data in anti-meridean

- package-lock.json
- package-release.json
- package.json
- src/contributors/MapContributor.ts
> Fix cast of serach source properties (map)

- src/contributors/HistogramContributor.ts
> Control on which collections trigger a histogram collaboration

- src/contributors/HistogramContributor.ts
- src/utils/histoswimUtils.ts
> Histogram: add maxBuckets notion to protects histograms from generating oversized number of buckets

- src/contributors/ComputeContributor.ts
> Add Count to metrics

- src/jsonSchemas/computeContributorConf.schema.json
> Fx field in metric could be null with count

- src/contributors/MapContributor.ts
> Fix: avoid same metric in request

- src/utils/utils.ts
- managing and handling special chars
> Use stringification of jsonpath lib to avoid

- src/contributors/MapContributor.ts
>  Fix shortlabels given by multiple sources

- src/contributors/HistogramContributor.ts
histogram changes its own updata data state
> Set the data update of the detailed histogram when the

- src/contributors/DetailedHistogramContributor.ts
> fix: detailed histogram does not adapt itself to the correct extend

- src/contributors/MapContributor.ts
Part of fix gisaia/ARLAS-wui#573
> fix: values of the legend contained NaN due to change in stats structure

- src/utils/mapUtils.ts
> Translate coordinate for clockwise polygons when longitudes

- package-lock.json
- package-release.json
- package.json
- src/contributors/MapContributor.ts
Fix https://github.com/gisaia/ARLAS-wui/issues/804
> Fix: undefined date field format

- src/contributors/ResultListContributor.ts
- src/jsonSchemas/resultlistContributorConf.schema.json
- src/models/models.ts
> feat: add details title configuration field

- src/contributors/MapContributor.ts
- src/models/models.ts
Fix gisaia/ARLAS-wui-builder#970
> fix: use proper typing for map contributor center

- src/utils/utils.ts
- test/app.js
Fix https://github.com/gisaia/ARLAS-wui-builder/issues/994
> Feat: allow all chars between quote for process

- src/contributors/MapContributor.ts
> fix: emit legend every time it is updated

- release-actions.sh
> Add release command to the chat's message

- src/contributors/MapContributor.ts
Fix https://github.com/gisaia/ARLAS-wui/issues/945
> Feat: fix meridian problem for agg geom

- src/contributors/MapContributor.ts
- src/utils/utils.ts
> fix(map): extract value or first array value from feature

- src/utils/utils.ts
> fix: properly remove idFieldName in search sort

- src/contributors/MapContributor.ts
- src/index.ts
- src/utils/mapUtils.ts
> fix: handle linestrings correctly at anti-meridian

- src/contributors/MapContributor.ts
- Fix #616
- Partial fix for gisaia/ARLAS-wui#967
-> Needs gisaia/ARLAS-web-components#975 for the edits
> fix: simplify geometries for geoFilters based on inclusion

- release-actions.sh
> enhance changelog

- src/contributors/ResultListContributor.ts
- src/index.ts
- src/models/models.ts
- Related to gisaia/ARLAS-wui#941 and gisaia/ARLAS-wui#942
> feat: add methods to check whether the visualisation of item is possible

- src/contributors/MapContributor.ts
- tsconfig.json
> feat: use geometry_path as default value for windowExtentGeometry

- src/contributors/ResultListContributor.ts
- Fix gisaia/ARLAS-wui-builder#1109
> fix: defining process on id column applies the process
